apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Standard EDB Postgres Advanced Server 10 Deployment Config
    iconClass: icon-postgresql
    tags: database,epas,postgres,postgresql
  name: edbas-persistent
objects:
  - apiVersion: v1
    stringData:
      password: '${PASSWORD}'
    kind: Secret
    metadata:
      name: '${NAME}-database-user-passwd'
    type: Opaque
  - apiVersion: v1
    stringData:
      password: '${PASSWORD}'
    kind: Secret
    metadata:
      name: '${NAME}-enterprisedb-passwd'
    type: Opaque
  - apiVersion: v1
    stringData:
      password: '${PASSWORD}'
    kind: Secret
    metadata:
      name: '${NAME}-repl-user-passwd'
    type: Opaque
parameters:
- name: NAME
- name: PASSWORD
  generate: expression
  from: '[a-z]{1}[a-zA-Z0-9]{6}[a-z]{1}'